// samples.js — the demo pack: one URL, fetched and handed to the importer.
//
// The demo is a real .somaplay file, generated by scripts/demo/gerar-demo.mjs
// from versioned sources. Loading it walks exactly the path a file shared by a
// friend walks, which is why this module builds no song of its own: a second way
// to create the demo would be a second thing to keep in sync.
//
// Deliberately NOT precached. The file is about 1 MB and every install would pay
// for it; the Service Worker caches it on the first fetch instead, so it crosses
// the network once. Offline and never fetched, this throws and the caller says so.
export const DEMO_URL = 'demo/soma_play-demo.somaplay';
const DEMO_FILE_NAME = 'soma_play-demo.somaplay';

export async function buscaDemo() {
  const res = await fetch(DEMO_URL);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return new File([await res.blob()], DEMO_FILE_NAME, { type: 'application/octet-stream' });
}
